### ISSUE TITLE
ObservedProperties appear to be duplicating

### ISSUE THREAD

**Issue by C-Loftus** [cgs-earth/OregonWaterDataPortal-ETL#12]
For some reason even though the pydantic model is generating a unique hash for the id it appears that FROST is incrementing it upon inserting if it already exists. Not clear why this is the case. Perhaps we need to not specify the other properties and just reference the iotid?

Write a test to catch this

**Comment by webb-ben** [comment]
I only see two observedProperties. is this wrong?

**Comment by C-Loftus** [comment]
There are only two names but the ids are incrementing so there are multiple ids. It appears that if you specify an ID for an observed property that is already defined and specify the name it adds a new one and autogenerates a new ID. 

I will test this further since it seems different behavior that I expected.

**Comment by C-Loftus** [comment]
Shouldbe resolved now
